services:
  redis:
    image: redis:latest
    container_name: test_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scoring_api
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=test_redis
      - REDIS_PORT=6379
      - PYTHONPATH=/src
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/healthcheck" ]
      interval: 10s
      timeout: 5s
      retries: 3
